# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release version

on:
  workflow_dispatch:
    inputs:
      bump_part:
        description: Part of the version number to be bumped up
        required: true
        default: minor
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

concurrency:
  group: release-version
  cancel-in-progress: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Configure git
        run: |
          git config user.name "Github Actions"
          git config user.email "<noreply@github.com>"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Lint with pylint
        run: |
          pylint magorder
      - name: Test with pytest
        run: |
          pytest -v --cov=./ --cov-report xml
      - name: Bump version ${{ inputs.bump_part }}
        run: |
          bumpversion --verbose ${{ inputs.bump_part }}
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Push to git
        run: |
          git push --all
          git push --tags
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          verbose: true
